### ISSUE TITLE
Recent Update: Alert icon count not working for me

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#19]
I received push alert fine, but not alert icon count.

**Comment by vbresults** [comment]
Unlike iOS which is ok with an add-on only update, we'll need to submit and wait for the updates of the android apps for this take effect.

**Comment by RoldanLT** [comment]
Ok, Thanks!

**Comment by vbresults** [comment]
Turns out badge numbers are simple for iOS, but in Android such functionality isn't standard, some phone manufacturers provide it, some don't, so as a general rule, popular apps like Facebook, Gmail, etc. use a sophisticated method where they hot swap the entire app icon with another graphic, which we cannot do at this time, so this new feature is restricted to iDevices.
