### ISSUE TITLE
App extremely slow and menu not appearing on iOS

### ISSUE THREAD

**Issue by DanHawk87** [vbresults/mobile-apps-for-xenforo#44]
On our Apex Online Racing app, the performance is absolutely poor. The page takes 1.4 seconds longer than chrome to load, 1.3 seconds longer than safari and 1.3 on Firefox.

Our members are complaining about the speed issue and typing issues (when they start typing nothing happens until they start a new paragraph - when performance is ultra poor)

Next up - On our iOS app, the menu from the side doesn't appear at all. Yet it appears on the mobile site in Safari and chrome.

Any help on the menu would be appreciated.

Additionally, a performance increase is needed.

**Comment by DanHawk87** [comment]
Just FYI - I managed to resolve the menu issue by running the "Alpha" software release.... cautious about using this though, so would like to know what's changed if poss (support for javascript/jQuery maybe?) 

Speed is still the same, a whole thread on my forum dedicated to members moaning about the speed:
(They say Android is WAYYYY worse than iOS)
http://apexonlineracing.com/community/threads/aor-app-crowd-funding-interest.10846/page-7#post-162376

**Comment by vbresults** [comment]
Dan, sorry you are experiencing so many issues; let's go into them one by one:

Please set your release back to Stable.  The other options are not meant for production sites and they will not work unless you've been instructed to use them -- and alerts will not work.

Next, there is a known issue with Audentio styles which heavily impacts performance.  Unlike full browsers, apps have certain restrictions, and there is a lot less room for coding inefficiencies.

As this is a problem with the style, it's not something we can fix.  Separate to that, the apps do not support fixed CSS positions, this is why the menu is behaving erratically.

For the purpose of measurement, set the app style to the default XenForo style in the Mobile Interface Options, and report any changes in performance.  Someone else did this and it was much faster.

I'd like to distinguish between performance and progress indication, which we exchanged messages about earlier -- it could seem like a performance issue since there's no progress indicator:

`One issue that we've been trying to address is the lack of a progress indicator or transition when going from one link to the next.  Another is that the page doesn't render until fully loaded (unlike Chrome).`

As I mentioned, we are working to a solution for 1.x.  This is already solved for PMA 2.0 (which we'll announce soon), which will be released in about a month.

**Comment by vbresults** [comment]
Update, which @bloh2 might be interested in too, the 1.x solution we've been working on is just about done for Android.  It has native browser performance and CSS fixed positions work now.

@DanHawk87 This was tested on AOR with multiple Android versions and works perfectly.  The Android version will be published to AOR in a few hours before any of the other apps.

When the iOS update is ready to be sent to apple, I'll post an update in this ticket, though apple's review process is much slower and it can take over from them to get to approving it.
