### ISSUE TITLE
After the recent update, Android 4.1.2 always crashing

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#49]
Android App in Problem: https://play.google.com/store/apps/details?id=net.phcorner.app
Device: S3 Mini Android 4.1.2

**Comment by vbresults** [comment]
The latest release was mistakenly built with only 4.2.x+ support; another update is going to hit the stores that adds back support for ICS and Jelly Bean 4.1.x; thank you for reporting (:

**Comment by vbresults** [comment]
Update: The latest release was built with only 4.2.x+ support; due to an upstream bug it crashes on lower 4.0 and 4.1.  We are waiting for the upstream issue to be fixed.

In the meantime, we will change the API levels so people can't install it on 4.0 and 4.1 until the issue is resolved.  An update is going to come in a few weeks that adds back support for ICS and Jelly Bean 4.1.

**Comment by vbresults** [comment]
Fixed in 1.1.42 (:

**Comment by RoldanLT** [comment]
So the current version on Google Play should work fine now?

**Comment by vbresults** [comment]
No, the current version on Google Play is 1.1.41, 1.1.42 is scheduled to be released by the end of the month

**Comment by RoldanLT** [comment]
I will wait for that. Thanks!

**Comment by vbresults** [comment]
@RoldanLT 1.2.0 is out, once your colors are set and add-on updated, post a ticket so we can get your app reactivated (:

**Comment by vbresults** [comment]
@RoldanLT Ping
