### ISSUE TITLE
Inconsistent results from push notifications .

### ISSUE THREAD

**Issue by cgunes** [vbresults/mobile-apps-for-xenforo#63]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### Did you verify this is a real problem by searching the [other tickets](https://github.com/vbresults/mobile-apps-for-xenforo/issues)?
Yes

### 1.1. If so, tell us about the problem
We are getting inconsistent results from push notifications. Sometimes they are delivered with some latency but sometimes they don't get delivered at all. What may be causing this and what should we do to have the push notifications working consistantly?

### 1.2. Which platform(s) does your issue occur on?
Android

### 1.3. Version numbers that your issue occurs with:

- Android App:  1.2.0
- Platform : XenForo
- Add-on Version: 1.2.0
- XenForo Version: 1.5.5

### 1.4. Please tell us how to recreate the issue in detail
Any situation which should send a push notification

### 1.5. Is there an error message involved?  If so, please paste
None

**Comment by vbresults** [comment]
There was some unscheduled maintenance today so some push alerts didn't process at all; but I will explain a bit about how the push system works -- it has a queue;

When someone generates an alert inside XenForo, it goes into the push alert queue.  This queue is then rolled up and sent to our remote push server on the next pageview to your XenForo site.

That's the 1st source of latency.

Depending on the connection between your server and our push server, there can be a little latency, like when visiting page on a browser.

That's the 2nd source of latency.

After we receive your queue/list of push messages to be sent out, we send them to either Google or Apple, since they are the ones that actually deliver it to the device.

That's the 3rd source of latency.

Sometimes, there is congestion at Google or Apple's end for a variety of reasons, and they delay the delivery of messages deliberately and process it when they see fit.

That's the 4th source of latency.

These all add together to the final latency you see.  We do everything we can to mitigate the delays on our end, and usually the delay is not really noticeable, but in some cases it might not be so.

**Comment by cgunes** [comment]
We are still experiencing problems with some of the push notifications not being delivered at all. This is random , some of them get delivered very fast , but some of them are lost and we are getting alot of complaints from our users because of this. 
Actually this is our most important problem with the mobile app. Please find a solution for this , we are getting alot of pressure from our members .

**Comment by vbresults** [comment]
Try this and report back: https://xenforo.com/community/resources/trigger-deferred-php-via-shell-crontab.2512/

This will make the push queue be sent to us every minute instead of when someone visits your forum which could be longer than a minute (for example, late at night when nobody is online)

**Comment by vbresults** [comment]
Edit: This problem today was due to a change we made on the push server, it should resume functioning again, thank you for reporting this -- but I do still recommend following the steps above to minimize the delay between alerts being made and sent

**Comment by cgunes** [comment]
I will ask my admin to make this change , because this is above my knowledge level :) and report back to you the results.
 Can this change also fix the randomly lost push notifications we experience. The delayed notifications can be tolerated but the complaints we get from members are about some notifications are lost and not delivered. This is an ongoing issue from when we started to use the app.

 Btw, thank you very much for your effort and time giving support to us :)
